insert into Notifications (Title, Content, TouristId, IsRead)
values('Welcome', 'Welcome to our app', '4b8dff80-ab3b-4cf2-a30c-94ac5334cd6d', 0)

select * from Tourists join Users On Tourists.UserId = Users.Id 

insert into Tourists(UserId) values('1f1918e2-e7c3-439c-8a30-3eda3b9be19e')

INSERT INTO Languages (Name, Code) VALUES
-- English Variants
('English (United States)', 'en-US'),
('English (United Kingdom)', 'en-GB'),
('English (Canada)', 'en-CA'),
('English (Australia)', 'en-AU'),

-- Arabic Variants
('Arabic (Egypt)', 'ar-EG'),
('Arabic (Saudi Arabia)', 'ar-SA'),
('Arabic (UAE)', 'ar-AE'),
('Arabic (Morocco)', 'ar-MA'),

-- French Variants
('French (France)', 'fr-FR'),
('French (Canada)', 'fr-CA'),
('French (Belgium)', 'fr-BE'),
('French (Switzerland)', 'fr-CH'),

-- Spanish Variants
('Spanish (Spain)', 'es-ES'),
('Spanish (Mexico)', 'es-MX'),
('Spanish (Argentina)', 'es-AR'),
('Spanish (Colombia)', 'es-CO'),

-- German Variants
('German (Germany)', 'de-DE'),
('German (Austria)', 'de-AT'),
('German (Switzerland)', 'de-CH'),

-- Portuguese Variants
('Portuguese (Portugal)', 'pt-PT'),
('Portuguese (Brazil)', 'pt-BR'),

-- Chinese Variants
('Chinese (Simplified, China)', 'zh-CN'),
('Chinese (Traditional, Taiwan)', 'zh-TW'),
('Chinese (Hong Kong)', 'zh-HK'),

-- Other Languages
('Japanese', 'ja-JP'),
('Korean', 'ko-KR'),
('Russian', 'ru-RU'),
('Turkish', 'tr-TR'),
('Hindi (India)', 'hi-IN'),
('Dutch (Netherlands)', 'nl-NL'),
('Swedish (Sweden)', 'sv-SE'),
('Polish (Poland)', 'pl-PL'),
('Greek (Greece)', 'el-GR'),
('Hebrew (Israel)', 'he-IL'),
('Thai (Thailand)', 'th-TH'),
('Vietnamese (Vietnam)', 'vi-VN'),
('Indonesian (Indonesia)', 'id-ID'),
('Malay (Malaysia)', 'ms-MY'),
('Bengali (Bangladesh)', 'bn-BD'),
('Urdu (Pakistan)', 'ur-PK'),
('Persian (Iran)', 'fa-IR'),
('Swahili (Kenya)', 'sw-KE'),
('Filipino (Philippines)', 'tl-PH');

UPDATE Nationalities SET Name = 'Afghanistan' WHERE Id = 1;
UPDATE Nationalities SET Name = 'Albania' WHERE Id = 2;
UPDATE Nationalities SET Name = 'Algeria' WHERE Id = 3;
UPDATE Nationalities SET Name = 'Andorra' WHERE Id = 4;

DECLARE @maxId INT;
SELECT @maxId = MAX(Id) FROM Nationalities;

DBCC CHECKIDENT ('Nationalities', RESEED, @maxId);

INSERT INTO Nationalities (Name) VALUES
('Angola'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahrain'),
('Bangladesh'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Estonia'),
('Ethiopia'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Guatemala'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kuwait'),
('Kyrgyzstan'),
('Latvia'),
('Lebanon'),
('Libya'),
('Lithuania'),
('Luxembourg'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Mexico'),
('Moldova'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar'),
('Namibia'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Korea'),
('Norway'),
('Oman'),
('Pakistan'),
('Palestine'),
('Panama'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Somalia'),
('South Africa'),
('South Korea'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tanzania'),
('Thailand'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');